import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { test } from 'node:test';
import { nameOf } from '../core/braceNames';
import { scanBraces } from '../core/braceScanner';
import { defaultScanSettings, weightsFrom } from '../core/scanSettings';
import { findPreset, presetWeights } from '../core/traitPresets';

/**
 * The whole point of this port, asserted.
 *
 * A brace's colour, personality and name are a pure function of a hash of its declaring
 * line — which means the same file opened in Visual Studio and in VS Code must hand the same
 * brace the same everything. That is only true if the two implementations agree bit for bit
 * on 64-bit FNV-1a, on the SplitMix64 finaliser, on every salt, on the order the trait table
 * is walked in, and on the lexer's idea of where a string ends.
 *
 * `test/fixtures/csharp-core.json` is what the C# `IdentityBraces.Core` makes of
 * `test/fixtures/sample.txt`, generated by `tools/parity` — which links the C# sources
 * directly rather than copying them. Regenerate it with:
 *
 *     cd tools/parity && dotnet run -c Release
 *
 * If this test fails after a change to either core, the two extensions have diverged and
 * everyone's braces have been reincarnated.
 */

const FIXTURES = path.join(__dirname, '..', '..', 'test', 'fixtures');

interface Expected {
    label: string;
    braces: Record<string, unknown>[];
}

function scenarios() {
    const settings = (independent: boolean, depth: boolean, warn: number) => {
        const s = defaultScanSettings();
        s.independentBraces = independent;
        s.colorByDepth = depth;
        s.complexityWarningDepth = warn;
        return s;
    };

    const unusable = () => {
        const s = defaultScanSettings();
        s.traitWeights = weightsFrom(presetWeights(findPreset('unusable')!));
        return s;
    };

    return [
        { label: 'default', settings: settings(true, false, 0) },
        { label: 'shared', settings: settings(false, false, 0) },
        { label: 'depth', settings: settings(true, true, 0) },
        { label: 'warn3', settings: settings(true, false, 3) },
        { label: 'unusable', settings: unusable() },
    ];
}

test('the TypeScript core agrees with the C# core, brace for brace', () => {
    const text = fs.readFileSync(path.join(FIXTURES, 'sample.txt'), 'utf8');
    const expected: Expected[] = JSON.parse(fs.readFileSync(path.join(FIXTURES, 'csharp-core.json'), 'utf8'));
    const scenarioList = scenarios();

    assert.equal(expected.length, scenarioList.length, 'fixture and scenario list are out of step');

    for (let i = 0; i < expected.length; i++) {
        const want = expected[i];
        const scenario = scenarioList[i];
        assert.equal(want.label, scenario.label);

        const got = scanBraces(text, scenario.settings);
        assert.equal(got.length, want.braces.length, `${want.label}: brace count`);

        for (let j = 0; j < got.length; j++) {
            const brace = got[j];
            const mine = {
                p: brace.position,
                c: brace.character,
                k: brace.kind,
                o: brace.isOpen ? 1 : 0,
                m: brace.isMatched ? 1 : 0,
                d: brace.depth,
                pi: brace.partnerIndex,
                pa: brace.parentIndex,
                id: hex(brace.idHi, brace.idLo),
                ci: brace.colorIndex,
                body: brace.traits.body,
                cr: brace.traits.creature,
                co: brace.traits.costume,
                mo: brace.traits.motion,
                ef: brace.traits.effects.slice(),
                name: nameOf(brace.idHi, brace.idLo),
            };

            assert.deepEqual(mine, want.braces[j], `${want.label}: brace ${j} at offset ${brace.position}`);
        }
    }
});

function hex(hi: number, lo: number): string {
    return `${(hi >>> 0).toString(16).padStart(8, '0')}${(lo >>> 0).toString(16).padStart(8, '0')}`;
}
