package identitybraces.core

import com.google.gson.JsonArray
import com.google.gson.JsonElement
import com.google.gson.JsonNull
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import com.google.gson.JsonPrimitive
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File

/**
 * The whole point of this port, asserted.
 *
 * A brace's colour, personality and name are a pure function of a hash of its declaring
 * line — which means the same file opened in Visual Studio, in VS Code and in a JetBrains
 * IDE must hand the same brace the same everything. That is only true if the implementations
 * agree bit for bit on 64-bit FNV-1a, on the SplitMix64 finaliser, on every salt, on the
 * order the trait table is walked in, and on the lexer's idea of where a string ends.
 *
 * `vscode/test/fixtures/csharp-core.json` is what the C# `IdentityBraces.Core` makes of
 * `sample.txt`, generated by `vscode/tools/parity` — which links the C# sources directly
 * rather than copying them. The VS Code port asserts against the same file. Regenerate it
 * after any change to any of the three cores:
 *
 *     cd vscode/tools/parity && dotnet run -c Release
 *
 * If this test fails, the ports have diverged and everyone's braces have been reincarnated.
 */
class ParityTest {
    private val fixtures = File(System.getProperty("identitybraces.fixtures") ?: "../vscode/test/fixtures")

    private class Scenario(val label: String, val settings: ScanSettings)

    private fun scenarios(): List<Scenario> {
        val unusable = ScanSettings(traitWeights = TraitCatalog.weightsFrom(TraitPresets.weightsOf(TraitPresets.find("unusable")!!)))

        return listOf(
            Scenario("default", ScanSettings(independentBraces = true, colorByDepth = false, complexityWarningDepth = 0)),
            Scenario("shared", ScanSettings(independentBraces = false, colorByDepth = false, complexityWarningDepth = 0)),
            Scenario("depth", ScanSettings(independentBraces = true, colorByDepth = true, complexityWarningDepth = 0)),
            Scenario("warn3", ScanSettings(independentBraces = true, colorByDepth = false, complexityWarningDepth = 3)),
            Scenario("unusable", unusable),
        )
    }

    @Test
    fun `the Kotlin core agrees with the C# core, brace for brace`() {
        val sample = File(fixtures, "sample.txt")
        val fixture = File(fixtures, "csharp-core.json")
        assertTrue(sample.isFile && fixture.isFile, "fixtures not found under ${fixtures.absolutePath}")

        val text = sample.readText()
        val expected = JsonParser.parseString(fixture.readText()).asJsonArray
        val scenarioList = scenarios()

        assertEquals(scenarioList.size, expected.size(), "fixture and scenario list are out of step")

        var checked = 0
        for (i in 0 until expected.size()) {
            val want = expected[i].asJsonObject
            val scenario = scenarioList[i]
            assertEquals(want["label"].asString, scenario.label)

            val got = BraceScanner.scan(text, scenario.settings)
            val wantBraces = want["braces"].asJsonArray
            assertEquals(wantBraces.size(), got.size, "${scenario.label}: brace count")

            for (j in got.indices) {
                val brace = got[j]
                val mine = JsonObject().apply {
                    addProperty("p", brace.position)
                    addProperty("c", brace.character.toString())
                    addProperty("k", brace.kind.ordinal)
                    addProperty("o", if (brace.isOpen) 1 else 0)
                    addProperty("m", if (brace.isMatched) 1 else 0)
                    addProperty("d", brace.depth)
                    addProperty("pi", brace.partnerIndex)
                    addProperty("pa", brace.parentIndex)
                    addProperty("id", Hash.hex(brace.identity))
                    addProperty("ci", brace.colorIndex)
                    add("body", nullable(brace.traits.body))
                    add("cr", nullable(brace.traits.creature))
                    add("co", nullable(brace.traits.costume))
                    add("mo", nullable(brace.traits.motion))
                    add("ef", JsonArray().also { array -> brace.traits.effects.forEach { array.add(it) } })
                    addProperty("name", BraceNames.of(brace.identity))
                }

                assertEquals(wantBraces[j], mine, "${scenario.label}: brace $j at offset ${brace.position}")
                checked++
            }
        }

        assertTrue(checked >= 400, "only $checked braces were compared; the fixture should hold 400")
    }

    private fun nullable(value: String?): JsonElement = if (value == null) JsonNull.INSTANCE else JsonPrimitive(value)
}
