import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "2.1.20"
    id("org.jetbrains.intellij.platform") version "2.6.0"
}

group = "com.github.turtleman31"
version = providers.gradleProperty("pluginVersion").get()

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        create(providers.gradleProperty("platformType"), providers.gradleProperty("platformVersion"))

        // The platform test framework, for the tests that open a real (headless) editor and
        // check what the plugin does to it. It is JUnit 4; the core tests are JUnit 5, and the
        // vintage engine runs both under one launcher.
        testFramework(TestFrameworkType.Platform)
    }

    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testImplementation("junit:junit:4.13.2")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// 2024.1 still runs on Java 17; everything after it runs on 21. Bytecode for 17 loads on both.
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17

        // The standard library comes from the IDE (see gradle.properties), and 2024.1's is
        // 1.9 — so that is the API surface this code is allowed to touch.
        apiVersion = KotlinVersion.KOTLIN_1_9
        languageVersion = KotlinVersion.KOTLIN_2_0
    }
}

// `./gradlew runRider` opens the plugin in a Rider sandbox instead of IntelliJ IDEA — the
// natural place to try it for anyone coming from the Visual Studio extension. Rider is a
// separate (large) download, fetched the first time the task runs.
intellijPlatformTesting {
    runIde {
        register("runRider") {
            type = IntelliJPlatformType.Rider
            version = providers.gradleProperty("riderVersion")
        }
    }
}

intellijPlatform {
    pluginConfiguration {
        version = providers.gradleProperty("pluginVersion")

        ideaVersion {
            sinceBuild = providers.gradleProperty("pluginSinceBuild")
            untilBuild = provider { null }
        }
    }

    // Nothing here has @NotNull contracts worth instrumenting, and skipping it keeps the
    // build free of a javac dependency on the IDE's own jars.
    instrumentCode = false
    buildSearchableOptions = false
}

tasks {
    runIde {
        // A sandbox that goes straight to the editor: no consent dialogs, no settings import
        // prompt, and whatever `-PopenPath=...` names opened on start.
        jvmArgs(
            "-Djb.consents.confirmation.enabled=false",
            "-Didea.initially.ask.config=never",
            "-Didea.suppress.statistics.report=true",
            "-Djb.privacy.policy.text=<!--999.999-->",
            "-Didea.is.internal=true",

            // The plugin's own debug lines — which scene the director cast and where — in
            // build/idea-sandbox/*/log/idea.log.
            "-Didea.log.debug.categories=#identitybraces",
        )

        providers.gradleProperty("openPath").orNull?.let { args(it) }
    }

    test {
        useJUnitPlatform()

        // The parity fixture is shared with the VS Code port and generated by the C# core —
        // see vscode/tools/parity. One fixture, one generator, three consumers.
        systemProperty("identitybraces.fixtures", rootDir.resolve("../vscode/test/fixtures").canonicalPath)
        systemProperty("identitybraces.reports", layout.buildDirectory.dir("reports/settings").get().asFile.path)

        testLogging {
            events("passed", "skipped", "failed")
            exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        }
    }
}
